{% set name = "duckdb" %}
{% set version = "1.5.5" %}

package:
  name: python-{{ name|lower }}-split
  version: {{ version }}

source:
  # The GitHub source is broken for v1.4.3
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72f33ee57ca7595b23957671a2cc7f7fe2be0ecc2d68f63abedcfcaa3a5c1238

build:
  number: 0
  skip: true  # [py<39]

outputs:
  - name: python-{{ name|lower }}
    script: build-duckdb.sh  # [unix]
    script: build-duckdb.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - python
        - pip
        - pybind11 >=2.6.0
        - scikit-build-core >=0.11.4
        - setuptools
        - setuptools_scm >=8.0
      run:
        - python
    test:
      imports:
        - duckdb
      requires:
        - pip
        # Enable the test suite when the github source is fixed
        # - pytest
        # - mypy
        # - fsspec
        # - google-cloud-storage
        # - pandas
      # source_files:
      #   - tools/pythonpkg/tests
      commands:
        - pip check
        # # Ensure we output UTF-8 on windows
        # - set PYTHONIOENCODING=utf-8  # [win]
        # # aarch64 is emulated and fails to run the test suite here
        # # Skip slow tests to avoid memory issues in CI, skip stub tests that is fragile under new version of mypy
        # - pytest -sv tools/pythonpkg/tests --ignore=tools/pythonpkg/tests/slow/ --ignore=tools/pythonpkg/tests/stubs/  # [not (ppc64le or aarch64)]
  - name: {{ name|lower }}
    build:
      noarch: generic
      skip: true  # [not linux64]
    requirements:
      run:
        - {{ pin_subpackage('python-duckdb', max_pin="x.x.x") }}
        - python
      host:
        - python
    test:
      imports:
        - duckdb
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://duckdb.org/docs/index.html
  dev_url: https://github.com/duckdb/duckdb-python

extra:
  recipe-maintainers:
    - jonashaag
    - sugatoray
    - dhirschfeld
    - xhochy
    - mariusvniekerk
    - gforsyth
